# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-05-08 03:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0003_mainshop'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket', models.CharField(max_length=64)),
                ('outtime', models.DateTimeField()),
                ('u_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.UserModel')),
            ],
            options={
                'db_table': 'axf_user_ticket',
            },
        ),
    ]
