# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-05-08 08:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0005_auto_20180508_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketmodel',
            name='outtime',
            field=models.IntegerField(),
        ),
    ]
