# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-05-08 09:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0006_auto_20180508_1649'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticketmodel',
            old_name='outtime',
            new_name='out_time',
        ),
    ]
