# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-05-07 02:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='u_email',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='u_imag',
            field=models.ImageField(default=1, upload_to='img'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='u_name',
            field=models.CharField(default=1, max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='u_pwd',
            field=models.CharField(default=1, max_length=80),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='user',
            table='asx_user',
        ),
    ]
