# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-05-07 03:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20180507_1039'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='u_sex',
            field=models.BooleanField(default=False),
        ),
    ]
