# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-05-04 14:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_user_s_addressee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='s_pwd',
            field=models.CharField(max_length=80),
        ),
    ]
